Update run_batch_mcorr_cnmf_pipeline.yml

diff --git a/.github/workflows/run_batch_mcorr_cnmf_pipeline.yml b/.github/workflows/run_batch_mcorr_cnmf_pipeline.yml
--- a/.github/workflows/run_batch_mcorr_cnmf_pipeline.yml
+++ b/.github/workflows/run_batch_mcorr_cnmf_pipeline.yml
@@ -70,7 +70,7 @@ jobs:
 
       - name: Deactivate conda environment
         run: |
-              conda deactivate
+              conda deactivate || echo "Environment not active or failed to deactivate"
 
       - name: Delete logs directory
         run: |
